import matplotlib.pyplot as plt
import scienceplots # noqa: F401
from pomaar.config import FIGURES_DIR

# Globally apply the IEEE style for all plots generated by this library
# You might need to install latex on Fedora: `rpm-ostree install texlive-scheme-basic`
# or temporarily comment this out if you don't have LaTeX yet.
try:
    plt.style.use(["science", "ieee"])
except Exception:
    # Fallback if scienceplots/latex is not ready
    pass

def save_plot(fig, filename: str):
    """Helper to save consistent figures to the report folder."""
    output_path = FIGURES_DIR / filename
    fig.savefig(output_path, dpi=300)
    print(f"Saved figure to {output_path}")

